name: DuelsParty
version: 1.0
main: org.antix.duelsparty.DuelsPartyPlugin
api-version: '1.21'
author: Antix
# Dodajemy opcjonalne, ale profesjonalne pola
description: "Zaawansowany system pojedynków 1v1 oraz Party z integracją MySQL."
website: https://github.com/antix/duelsparty

commands:
  duel:
    description: "Główna komenda gracza (wyzwania, akceptacja, statystyki, grupy)"
    aliases: [d]
    permission: duelsparty.user
    # Nie definiujemy 'usage', ponieważ Dispatcher sam wysyła pomoc zależną od języka
  dueladmin:
    description: "Centrum zarządzania pluginem (arenami, zestawami, konfiguracją)"
    aliases: [da, pduel]
    permission: duelsparty.admin

permissions:
  duelsparty.user:
    description: "Dostęp do podstawowych funkcji pojedynków"
    default: true
  duelsparty.admin:
    description: "Pełny dostęp do konfiguracji aren i zestawów"
    default: op